image: node:10.15.3

stages:
  - staging

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-staging:
  stage: staging
  environment:
    name: staging
  only:
    - staging
  script:
    - npm install -g firebase-tools
    - firebase -V
    - npm install
    - CI=false npm run build
    - firebase use busha-pay  --token $FTOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FTOKEN
  variables:
    REACT_APP_AUTH: $REACT_APP_AUTH
    REACT_APP_BASE: $REACT_APP_BASE
    REACT_APP_LOGO: $REACT_APP_LOGO
    REACT_APP_ACCOUNT: $REACT_APP_ACCOUNT
